#!/bin/bash

app='basic'
tests="
ProcessorsTest 
SchedulerTest
"

for test in `echo $tests`
do
	python manage.py test $app.$test
done

app='scraper'
tests="
ScraperRunTest.test_missing_base_elem
ScraperRunTest.test_missing_url_elem
ScraperRunTest.test_scraper
ScraperRunTest.test_standard_field_as_follow_url_hack
ScraperRunTest.test_testmode
ScraperRunTest.test_task_run_type
ScraperRunTest.test_no_task_run_type
ScraperRunTest.test_max_items_read
ScraperRunTest.test_max_items_save
ScraperRunTest.test_missing_mandatory
ScraperRunTest.test_processor
ScraperRunTest.test_reg_exp
ScraperRunTest.test_with_imgs
CheckerRunTest.test_keep_video
CheckerRunTest.test_404_delete
CheckerRunTest.test_404_delete_with_zero_actions
CheckerRunTest.test_404_delete_with_img
CheckerRunTest.test_x_path_delete
CheckerRunTest.test_checker_test_wrong_checker_config
PaginationTest.test_config_append_str_without_page
PaginationTest.test_p_on_start
PaginationTest.test_range_funct_type_wrong_replace_format
PaginationTest.test_range_funct_type_one_page
PaginationTest.test_free_list_type_wrong_replace_format
PaginationTest.test_free_list_type_scraper_run
ModelTest.test_scraper_get_scrape_elems
ModelTest.test_scraper_get_mandatory_scrape_elems
"

for test in `echo $tests`
do
	python manage.py test $app.$test
done

