# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-06-09 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_scraper', '0018_added_use_default_procs_field_to_scraper_elems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestpagetype',
            name='body',
            field=models.TextField(blank=True, help_text='Optional HTTP message body provided as a unicode string, can use {main page attribute} and {page} placeholders.'),
        ),
        migrations.AlterField(
            model_name='requestpagetype',
            name='cookies',
            field=models.TextField(blank=True, help_text='Optional cookies as JSON dict (use double quotes!), can use {main page attribute} and {page} placeholders.'),
        ),
        migrations.AlterField(
            model_name='requestpagetype',
            name='form_data',
            field=models.TextField(blank=True, help_text='Optional HTML form data as JSON dict (use double quotes!), only used with FormRequest request type, can use {main page attribute} and {page} placeholders.'),
        ),
        migrations.AlterField(
            model_name='requestpagetype',
            name='headers',
            field=models.TextField(blank=True, help_text='Optional HTTP headers sent with each request, provided as a JSON dict (e.g. {"Referer":"http://referer_url"}, use double quotes!)), can use {main page attribute} and {page} placeholders.'),
        ),
    ]
