# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-06-12 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_scraper', '0019_updated_help_texts_for_request_info_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='work_status',
            field=models.CharField(choices=[('R2', 'REVISION NEEDED (MAJOR)'), ('R1', 'REVISION NEEDED (MINOR)'), ('BR', 'BROKEN'), ('W', 'WORKING'), ('RC', 'RELEASE CANDIDATE'), ('BE', 'BETA'), ('A', 'ALPHA'), ('D', 'DRAFT'), ('S', 'SUSPENDED'), ('U', 'UNKNOWN'), ('N', 'NOT SET')], default='N', max_length=2),
        ),
    ]
