# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-06-12 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_scraper', '0020_added_work_status_field_to_scraper'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='owner',
            field=models.CharField(blank=True, help_text='Optional owner when working on scrapers with various people', max_length=12),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='status',
            field=models.CharField(choices=[('A', 'ACTIVE'), ('M', 'MANUAL'), ('P', 'PAUSED'), ('I', 'INACTIVE')], default='P', help_text='Runtime status of the scraper, used by scheduling mechanism.', max_length=1),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='work_status',
            field=models.CharField(choices=[('R2', 'REVISION NEEDED (MAJOR)'), ('R1', 'REVISION NEEDED (MINOR)'), ('BR', 'BROKEN'), ('W', 'WORKING'), ('RC', 'RELEASE CANDIDATE'), ('BE', 'BETA'), ('A', 'ALPHA'), ('D', 'DRAFT'), ('S', 'SUSPENDED'), ('U', 'UNKNOWN'), ('N', 'NOT SET')], default='N', help_text='Internal work/progress status of the scraper.', max_length=2),
        ),
    ]
