# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-06-13 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_scraper', '0021_added_owner_field_to_scraper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraper',
            name='work_status',
            field=models.CharField(choices=[('R2', 'REVISION NEEDED (MAJOR)'), ('R1', 'REVISION NEEDED (MINOR)'), ('UR', 'UNRESOLVED'), ('BR', 'BROKEN'), ('W', 'WORKING'), ('RC', 'RELEASE CANDIDATE'), ('BE', 'BETA'), ('A', 'ALPHA'), ('D', 'DRAFT'), ('S', 'SUSPENDED'), ('U', 'UNKNOWN'), ('N', 'NOT SET')], default='N', help_text='Internal work/progress status of the scraper.', max_length=2),
        ),
    ]
