# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-06-14 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_scraper', '0022_added_option_for_scraper_work_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='follow_pages_by_xpath',
            field=models.TextField(blank=True, help_text='Optional, follow links from a single non-paginated or all statically paginated (RANGE_FUNCT, FREE_LIST) main pages'),
        ),
        migrations.AddField(
            model_name='scraper',
            name='num_pages_follow',
            field=models.IntegerField(blank=True, help_text='Optionally limit number of pages to follow (default: follow until XPath fails)', null=True),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='pagination_type',
            field=models.CharField(choices=[('N', 'NONE'), ('R', 'RANGE_FUNCT (+FOLLOW)'), ('F', 'FREE_LIST (+FOLLOW)'), ('O', 'FOLLOW')], default='N', max_length=1),
        ),
    ]
