# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-06-23 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_scraper', '0024_new_follow_page_type_choice_for_rpt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scraper',
            old_name='follow_pages_by_xpath',
            new_name='follow_pages_url_xpath',
        ),
        migrations.AddField(
            model_name='scraper',
            name='follow_pages_page_xpath',
            field=models.TextField(blank=True, help_text='Optional additional XPath for the page number, can be used in {follow_page} placeholder.'),
        ),
        migrations.AlterField(
            model_name='requestpagetype',
            name='body',
            field=models.TextField(blank=True, help_text='Optional HTTP message body provided as a unicode string, can use {main page attribute}, {page} and {follow_page} placeholders.'),
        ),
        migrations.AlterField(
            model_name='requestpagetype',
            name='cookies',
            field=models.TextField(blank=True, help_text='Optional cookies as JSON dict (use double quotes!), can use {main page attribute}, {page} and {follow_page} placeholders.'),
        ),
        migrations.AlterField(
            model_name='requestpagetype',
            name='form_data',
            field=models.TextField(blank=True, help_text='Optional HTML form data as JSON dict (use double quotes!), only used with FormRequest request type, can use {main page attribute}, {page} and {follow_page} placeholders.'),
        ),
        migrations.AlterField(
            model_name='requestpagetype',
            name='headers',
            field=models.TextField(blank=True, help_text='Optional HTTP headers sent with each request, provided as a JSON dict (e.g. {"Referer":"http://referer_url"}, use double quotes!)), can use {main page attribute}, {page} and {follow_page} placeholders.'),
        ),
    ]
